namespace SmartAnalysis.Visualization.Colormaps;

/// <summary>A colormap paired with its display name (for a palette picker).</summary>
public sealed record NamedColormap(string Name, Colormap Map);

/// <summary>
/// The predefined AFM data colormaps, a clean-room reimplementation of the legacy palette set (256-entry
/// procedural LUTs) so the look matches legacy SmartAnalysis while the code is first-party. Each entry is
/// generated by the legacy per-index formula (component = <c>CutOff(f(i))</c>). Theme-independent (ADR-008):
/// Light/Dark never changes the data colormap. The complex table/enhancer-based legacy maps (Contrast,
/// Terrain, Seismic, Rose, …) are a follow-up; this ships the clean formula-based set.
/// </summary>
public static class ColormapCatalog
{
    private const int N = Colormap.Size; // 256

    /// <summary>All predefined colormaps, in display order (Gold first — the AFM default).</summary>
    public static IReadOnlyList<NamedColormap> All { get; } =
    [
        new NamedColormap("Gold", Colormap.FromGenerator(GoldAt)),
        new NamedColormap("Grayscale", Colormap.FromGenerator(i => new Rgb((byte)i, (byte)i, (byte)i))),
        new NamedColormap("Aqua", Colormap.FromGenerator(AquaAt)),
        new NamedColormap("Brown", Colormap.FromGenerator(BrownAt)),
        new NamedColormap("Melon", Colormap.FromGenerator(MelonAt)),
        new NamedColormap("Red", Colormap.FromGenerator(RedAt)),
        new NamedColormap("Green", Colormap.FromGenerator(GreenAt)),
    ];

    /// <summary>The default colormap (Gold).</summary>
    public static NamedColormap Default => All[0];

    /// <summary>The display names in order (for a picker).</summary>
    public static IReadOnlyList<string> Names { get; } = [.. All.Select(c => c.Name)];

    /// <summary>Resolves a colormap by name (case-insensitive); the <see cref="Default"/> map when unknown.</summary>
    public static Colormap ByName(string? name)
    {
        foreach (var entry in All)
        {
            if (string.Equals(entry.Name, name, StringComparison.OrdinalIgnoreCase))
            {
                return entry.Map;
            }
        }

        return Default.Map;
    }

    // Clamp a real component to a byte (legacy CutOff).
    private static byte CutOff(double v) => v <= 0.0 ? (byte)0 : v >= 255.0 ? (byte)255 : (byte)v;

    // Legacy formulas (SIZE == N == 256), reimplemented per index.
    private static Rgb GoldAt(int i) => new(CutOff(i * 2), CutOff((i * 2) - (N / 2.0)), CutOff((i * 2) - N));

    private static Rgb MelonAt(int i)
        => new(CutOff((i * 2) - (N / 2.0)), CutOff((i * 2) - (N * 0.15)), CutOff((i * 2) - (N * 0.9)));

    private static Rgb AquaAt(int i)
    {
        double p = (double)i / N;
        return new Rgb(CutOff(((2 * p) - 1.0) * N), CutOff(((2 * p) - 0.5) * N), CutOff(2 * p * N));
    }

    private static Rgb BrownAt(int i)
    {
        double p = (double)i / N;
        return new Rgb(CutOff(p * N), CutOff(((p * 1.5) - 0.5) * N), CutOff(((p * 3.0) - 2.0) * N));
    }

    private static Rgb RedAt(int i)
        => i < N / 2
            ? new Rgb(CutOff(i * 2), 0, 0)
            : new Rgb(CutOff(i * 2), CutOff((i - (N / 2)) * 2), CutOff((i - (N / 2)) * 2));

    private static Rgb GreenAt(int i)
        => i < N / 2
            ? new Rgb(0, CutOff(i * 2), 0)
            : new Rgb(CutOff((i - (N / 2)) * 2), CutOff(i * 2), CutOff((i - (N / 2)) * 2));
}
